# Build settings

# Name of your site (displayed in the header)
name: Surya Santoso

# Short bio or description (displayed in the header)
description: Web Developer

markdown: kramdown
permalink: /:title/

sass:
  sass_dir: assets/css
  style: :nested